default:
	py C:\Users\KR\PycharmProjects\Capstone\src\controller.py "C:\Users\KR\PycharmProjects\Capstone\input_files\if_to_switch\t2.c"
clean:
	del ..\src\parser.out ..\src\parsetab.py ..\src\temp.c
	rmdir /S /Q ..\src\__pycache__
