default:
	py C:\Users\KR\PycharmProjects\Capstone\src\controller.py "C:\Users\KR\PycharmProjects\Capstone\input_files\t2"


clean:
	del ..\src\parser.out ..\src\parsetab.py ..\src\temp.c
	rmdir /S /Q ..\src\__pycache__


#C:\GnuWin32\bin\indent -linux "C:\Users\KR\PycharmProjects\Capstone\env\temp.c"
# C:\Users\KR\Downloads\AStyle_3.1_windows\AStyle\bin\Astyle.exe C:\Users\KR\PycharmProjects\Capstone\env\temp_here.c