default:
	py C:\Users\KR\PycharmProjects\Capstone\src\controller.py "C:\Users\KR\PycharmProjects\Capstone\input_files\if_to_switch\t17.c"
	C:\GnuWin32\bin\indent -linux "C:\Users\KR\PycharmProjects\Capstone\env\temp_here.c"
clean:
	del ..\src\parser.out ..\src\parsetab.py ..\src\temp.c
	rmdir /S /Q ..\src\__pycache__
